default_job = "run"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false
watch = ["src", "Cargo.toml"]

[jobs.run]
command = ["cargo", "run"]
watch = ["src", "Cargo.toml", "bacon.toml", ".env", ".env.local"]
need_stdout = true
allow_warnings = true

[jobs.test]
command = ["cargo", "test"]
need_stdout = true
allow_failures = true
watch = ["src", "Cargo.toml"]
